#pragma once
#include <stdbool.h>
#include <stdint.h>

#define PODCAST_IDLE_RETURN_US INT64_C(7000000)
#define PODCAST_IDLE_SCREEN_OFF_SECONDS 15U
#define PODCAST_IDLE_WAKE_PRESS_GAP_US INT64_C(900000)

/* The caller owns the monotonic activity stamp. Update it at the button
 * callback entry, including PRESS and the immediate transport/volume paths.
 * This helper performs no IO and changes neither playback nor seek position. */
typedef struct {
    int64_t now_us;
    int64_t last_input_us;
    unsigned screen_off_seconds; /* Zero disables automatic screen-off. */
    bool live_playback;          /* Matching PLAYING or BUFFERING session. */
    bool away_from_player;
    bool protected_view;         /* Protect navigation, not screen-off. */
    bool screen_awake;
} podcast_idle_input_t;

typedef struct {
    bool return_to_player;
    bool turn_screen_off;
} podcast_idle_decision_t;

static inline podcast_idle_decision_t podcast_idle_decide(podcast_idle_input_t in)
{
    podcast_idle_decision_t out = {0};
    /* Reject regressed/invalid clocks instead of underflowing into a timeout.
     * Nonnegative subtraction in unsigned space also avoids signed overflow. */
    if (in.now_us < 0 || in.last_input_us < 0 || in.now_us < in.last_input_us) return out;
    const uint64_t idle_us = (uint64_t)in.now_us - (uint64_t)in.last_input_us;
    out.return_to_player = in.live_playback && in.away_from_player && !in.protected_view &&
                           idle_us >= (uint64_t)PODCAST_IDLE_RETURN_US;
    out.turn_screen_off = in.screen_awake && in.screen_off_seconds &&
                          idle_us >= (uint64_t)in.screen_off_seconds * UINT64_C(1000000);
    return out;
}

/* PRESS wakes immediately. The CLICK/LONG/DOUBLE generated by that press must
 * not pause audio, change volume, navigate, or apply an unfinished seek.
 * BSP emits no release event; CLICK/DOUBLE finish their gesture, while LONG
 * suppression ends at the next PRESS (the first press of a new gesture).
 * A second PRESS before DOUBLE still belongs to the wake gesture. The current
 * BSP uses 500ms LONG and a 180ms multi-click window; a new PRESS after 900ms
 * cannot be part of the prior short gesture. This also releases three-or-more
 * clicks, whose terminal MULTIPLE_CLICK event is not exposed by the BSP. */
typedef enum {
    PODCAST_IDLE_KEY_PRESS,
    PODCAST_IDLE_KEY_CLICK,
    PODCAST_IDLE_KEY_DOUBLE,
    PODCAST_IDLE_KEY_LONG,
    PODCAST_IDLE_KEY_OTHER,
} podcast_idle_key_t;

typedef enum {
    PODCAST_IDLE_WAKE_NONE,
    PODCAST_IDLE_WAKE_PENDING,
    PODCAST_IDLE_WAKE_LONG,
} podcast_idle_wake_phase_t;

typedef struct {
    podcast_idle_wake_phase_t phase;
    int64_t last_press_us;
} podcast_idle_wake_t;

typedef struct {
    bool request_wake;
    bool consume;
} podcast_idle_key_decision_t;

/* Only the button callback owns this guard. Request screen work in its worker;
 * never call LVGL, panel IO, networking, or storage from the button callback. */
static inline podcast_idle_key_decision_t podcast_idle_wake_input(
    podcast_idle_wake_t *guard, podcast_idle_key_t key, bool screen_awake,
    int64_t now_us)
{
    podcast_idle_key_decision_t out = {0};
    if (!guard || key == PODCAST_IDLE_KEY_OTHER) return out;

    if (guard->phase == PODCAST_IDLE_WAKE_PENDING) {
        const bool new_gesture = key == PODCAST_IDLE_KEY_PRESS && screen_awake &&
            now_us >= 0 && guard->last_press_us >= 0 && now_us >= guard->last_press_us &&
            (uint64_t)now_us - (uint64_t)guard->last_press_us >=
                (uint64_t)PODCAST_IDLE_WAKE_PRESS_GAP_US;
        if (new_gesture) guard->phase = PODCAST_IDLE_WAKE_NONE;
        else {
            out.consume = true;
            if (key == PODCAST_IDLE_KEY_PRESS) guard->last_press_us = now_us;
            if (key == PODCAST_IDLE_KEY_CLICK || key == PODCAST_IDLE_KEY_DOUBLE)
                guard->phase = PODCAST_IDLE_WAKE_NONE;
            else if (key == PODCAST_IDLE_KEY_LONG)
                guard->phase = PODCAST_IDLE_WAKE_LONG;
            return out;
        }
    }
    if (guard->phase == PODCAST_IDLE_WAKE_LONG) {
        if (key != PODCAST_IDLE_KEY_PRESS) {
            out.consume = true;
            if (key == PODCAST_IDLE_KEY_CLICK || key == PODCAST_IDLE_KEY_DOUBLE)
                guard->phase = PODCAST_IDLE_WAKE_NONE;
            return out;
        }
        guard->phase = PODCAST_IDLE_WAKE_NONE;
    }
    if (!screen_awake) {
        out.request_wake = true;
        out.consume = true;
        guard->phase = key == PODCAST_IDLE_KEY_PRESS ? PODCAST_IDLE_WAKE_PENDING :
                       key == PODCAST_IDLE_KEY_LONG ? PODCAST_IDLE_WAKE_LONG :
                       PODCAST_IDLE_WAKE_NONE;
        if (key == PODCAST_IDLE_KEY_PRESS) guard->last_press_us = now_us;
    }
    return out;
}
