#!/usr/bin/env python3
"""Generate original, neutral ROM artwork without network access or source images."""
import hashlib
import json
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets/images/podcast-covers"
PUBLIC = ROOT.parent / "assets/publication/neutral-covers"
SIZES = (112, 48)
# Existing source identifiers are retained for application compatibility only.
IDS = ("gushifen", "huzuoyou", "buheshiyi", "guixian101", "yeelok", "tianzhen",
       "lidan", "zhangxiaojun", "luoyonghao", "wechat-talk", "thatisbiz",
       "src_5f90a6b1eacd7a9c")


def digest(data):
    return hashlib.sha256(data).hexdigest()


def tile(size, variant):
    """An original sound-wave symbol; no publisher art is read or reproduced."""
    blue, white = (0, 99, 242), (255, 255, 255)
    pixels = bytearray()
    for y in range(size):
        for x in range(size):
            u, v = (x + .5) / size, (y + .5) / size
            color = blue
            radius = ((u - .5) ** 2 + (v - .5) ** 2) ** .5
            if .345 <= radius <= .365:
                color = (106, 164, 250)
            for i in range(5):
                centre = .30 + i * .10
                half_height = (.09, .16, .23, .16, .09)[i]
                if variant % 3 == 1:
                    half_height = (.18, .11, .23, .11, .18)[i]
                elif variant % 3 == 2:
                    half_height = (.10, .19, .14, .23, .10)[i]
                if abs(u - centre) <= .025 and abs(v - .5) <= half_height:
                    color = white
            if (u - (.77 if variant % 2 else .23)) ** 2 + (v - .22) ** 2 <= .026 ** 2:
                color = white
            pixels.extend(color)
    rgb565 = bytearray()
    exact_rgb = bytearray()
    for offset in range(0, len(pixels), 3):
        r, g, b = pixels[offset:offset + 3]
        encoded = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        rgb565.extend(struct.pack("<H", encoded))
        exact_rgb.extend((((encoded >> 11) & 31) * 255 // 31,
                          ((encoded >> 5) & 63) * 255 // 63,
                          (encoded & 31) * 255 // 31))
    return bytes(rgb565), bytes(exact_rgb)


def png(size, rgb):
    def chunk(kind, content):
        return (struct.pack(">I", len(content)) + kind + content +
                struct.pack(">I", zlib.crc32(kind + content)))
    scanlines = b"".join(b"\0" + rgb[y * size * 3:(y + 1) * size * 3]
                         for y in range(size))
    return (b"\x89PNG\r\n\x1a\n" +
            chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0)) +
            chunk(b"IDAT", zlib.compress(scanlines, 9)) + chunk(b"IEND", b""))


def descriptor(symbol, size, raw):
    lines = [f"_Alignas(4) static const uint8_t {symbol}_pixels[] = {{"]
    lines.extend("    " + ",".join(f"0x{b:02x}" for b in raw[i:i + 24]) + ","
                 for i in range(0, len(raw), 24))
    lines += ["};", f"static const lv_image_dsc_t {symbol} = {{",
              f"    .header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565, .flags = 0, .w = {size}, .h = {size}, .stride = {size * 2}}},",
              f"    .data_size = sizeof({symbol}_pixels), .data = {symbol}_pixels", "};", ""]
    return "\n".join(lines)


def generate():
    ASSETS.mkdir(parents=True, exist_ok=True)
    PUBLIC.mkdir(parents=True, exist_ok=True)
    output = ["/* Original neutral tiles, generated by tools/generate_podcast_covers.py. */",
              '#include "podcast_covers.h"', "#include <string.h>", ""]
    records, bindings, byte_count = [], [], 0
    # Host-only fixture wires use the same validated format as production covers.
    for variant, identity in enumerate(IDS[:3]):
        raw, _ = tile(52, variant)
        wire = (b"PDC1" + struct.pack("<HHII", 52, 52, len(raw), zlib.crc32(raw)) +
                hashlib.sha256(raw).digest()[:16] + raw)
        (PUBLIC / f"neutral-{identity}-52.pdc1").write_bytes(wire)
    for variant, identity in enumerate((*IDS, "default")):
        stem = identity.replace("-", "_")
        record = {"id": identity, "source": "Original procedural sound-wave tile",
                  "license": "MIT; see repository LICENSE", "prepared": {}}
        for size in SIZES:
            raw, rgb = tile(size, variant)
            output.append(descriptor(f"cover_{stem}_{size}", size, raw))
            # New outputs never overwrite the private publisher artwork files.
            filename = f"neutral-{identity}-{size}.png"
            (PUBLIC / filename).write_bytes(png(size, rgb))
            record["prepared"][str(size)] = {"rgb565_sha256": digest(raw),
                                             "bytes": len(raw),
                                             "preview": f"assets/publication/neutral-covers/{filename}"}
            byte_count += len(raw)
        if identity != "default":
            bindings.append(f'    {{"{identity}", &cover_{stem}_112, &cover_{stem}_48}},')
        records.append(record)
    output += ["static const struct { const char *id; const lv_image_dsc_t *large, *small; } covers[] = {",
               *bindings, "};", "", "const lv_image_dsc_t *podcast_cover_get(const char *show_id, bool thumbnail)", "{",
               "    if (show_id) for (unsigned i = 0; i < sizeof(covers) / sizeof(covers[0]); ++i)",
               "        if (!strcmp(show_id, covers[i].id)) return thumbnail ? covers[i].small : covers[i].large;",
               "    return thumbnail ? &cover_default_48 : &cover_default_112;", "}"]
    destination = ROOT / "main/podcast_covers.c"
    pending = destination.with_suffix(".c.pending")
    pending.write_text("\n".join(output) + "\n")
    pending.replace(destination)
    (ASSETS / "manifest.json").write_text(json.dumps({"artwork_policy": "original-neutral", "artworks": [],
       "neutral_tiles": records, "sizes": list(SIZES),
       "rgb565_total_bytes_including_neutral_fallback": byte_count}, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps({"neutral_covers": len(records), "native_sizes": list(SIZES),
                      "rom_bytes": byte_count, "network_access": False}))


if __name__ == "__main__":
    generate()
